### ISSUE TITLE
Slow!!

### ISSUE THREAD

**Issue by devxpy** [zakkak/workspace-grid#43] opened 2017-10-20 19:13 UTC
The workspace indicator dialog seems to stay there for a long time after I am done with switching..

It's not a dealbreaker but an obstruction when you're trying to work fast.

Thanks for this extension btw, greatly improves on the default workspaces../

**Comment by zakkak** [comment] 2017-10-20 20:58
Duplicate of #42

**Closed by zakkak** 2017-10-20 20:58 UTC

**Comment by devxpy** [comment] 2017-10-20 23:02
sorry to waste your time
