### ISSUE TITLE
Show workspace miniatures at bottom when grid layout is all horizontal

### ISSUE THREAD

**Issue by stephan-henningsen** [zakkak/workspace-grid#91] opened 2018-09-25 07:55 UTC
Hi,

This feature actually used to exist in the plugin, but was removed. Perhaps by accident? If not, please back-port it and add is as an option.

The thing is that I have a 8×1 grid layout of workspaces, that is 8 in a horizontal row.  When I press Super and all workspaces are minimized, the screen gets split in two; to the right I see minimized versions of all apps on the selected workspace, and to the right I see my row of workspaces:

[ windows | workspaces ]

While the orientation might make sense with other grid layouts, it is definitely leads to waste of precious space when all workspaces are aligned horizontally.  See screenshot and I think you'll agree.

The fix is easy: Place the two screen halves above each other:

 windows
---------------
workspaces

Instead of trying to make some clever logic that determines when to use which layout, do the easy thing:

Make an option switch.

I suppose this wouldn't hurt: useAlternativeLayout = gridLayout.x > gridLayout.y;

Anyway, please look into this. Like I said, this used to work, but suddently broke which is really frustrating.

![image](https://user-images.githubusercontent.com/7459151/46000598-57369100-c0a9-11e8-8551-60c614df2cc5.png)

**Comment by zakkak** [comment] 2018-09-25 11:47
Duplicate of #64 

> This feature actually used to exist in the plugin, but was removed. Perhaps by accident?

I don't recall this. Can you be more specific? On which version for instance or even which year.

> The fix is easy: Place the two screen halves above each other

PRs are welcome

**Closed by zakkak** 2018-09-25 11:47 UTC
